version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Say hello
          command: echo "Hello To My World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only: main
